services:
  alloy:
    image: grafana/alloy:v1.9.0-rc.1
    hostname: alloy
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "12345:12345" # Alloy UI
      - "9999:9999" # Prometheus metrics from OTEL
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro # For service discovery
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/config.alloy"]
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.3.0
    hostname: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/etc/prometheus
    # command: [ "--config.file=/etc/prometheus/prometheus.yml" ]
    # command: [ "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/etc/prometheus/console_libraries", "--web.console.templates=/etc/prometheus/consoles", "--web.enable-lifecycle" ]
    # depends_on:
    #   - init_prometheus
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/etc/prometheus/console_libraries"
    - "--web.console.templates=/etc/prometheus/consoles"
    - "--web.enable-lifecycle"
    - "--web.enable-admin-api" # Enable admin API
    - "--storage.tsdb.retention.time=7d" # Set retention
    - "--web.enable-remote-write-receiver" # Enable remote write receiver
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.7.2
    hostname: tempo
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    command: [ "/tempo", "-config.file=/etc/tempo.yaml" ]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
          cpus: '0.2'
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.5
    hostname: loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/loki/local-config.yaml
      - -config.expand-env=true
    networks:
      - monitoring

  pyroscope:
    image: grafana/pyroscope:1.9.0
    hostname: pyroscope
    ports:
      - "4040:4040"
    volumes:
      - pyroscope-data:/data
    environment:
      - PYROSCOPE_LOG_LEVEL=info
    command:
      - "-target=all"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.0.1
    hostname: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_METRICS_ENABLED=true # Enable Grafana metrics
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor # Enable TraceQL editor
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      - grafana-storage:/var/lib/grafana
    labels:
      - "monitoring.scrape=true"
      - "monitoring.port=3000"
      - "monitoring.path=/metrics"
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - monitoring

volumes:
  grafana-storage:
  tempo-data:
  loki-data:
  prometheus-data:
  pyroscope-data:


networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
