services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.123.0
    hostname: otel-collector
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config", "/etc/otel-collector-config.yaml" ]
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.3.0
    hostname: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/etc/prometheus
    command: [ "--config.file=/etc/prometheus/prometheus.yml"]
    # command: [ "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/etc/prometheus/console_libraries", "--web.console.templates=/etc/prometheus/consoles", "--web.enable-lifecycle" ]
    # depends_on:
    #   - init_prometheus
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.7.2
    hostname: tempo
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    command: [ "/tempo", "-config.file=/etc/tempo.yaml" ]
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
          cpus: '0.1'
    networks:
      - monitoring

  loki:
    image: grafana/loki:3.5
    hostname: loki
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  pyroscope:
    image: grafana/pyroscope:1.9.0
    hostname: pyroscope
    ports:
      - "4040:4040"
    volumes:
      - pyroscope-data:/data
    environment:
      - PYROSCOPE_LOG_LEVEL=info
    command:
      - "-target=all"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:12.0.1
    hostname: grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:rw
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - monitoring

volumes:
  grafana-storage:
  tempo-data:
  loki-data:
  prometheus-data:
  pyroscope-data:


networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
