global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      # - targets: ["srv-captain--otel-collector:9999"]
      - targets: ["otel-collector:9999"]
        labels:
          env: "prod"
          component: "collector"
