global:
  scrape_interval: 5s   # Much faster - was 15s
  evaluation_interval: 5s  # Much faster - was 15s
  scrape_timeout: 5s    # Keep timeout reasonable

scrape_configs:
  - job_name: "alloy"
    static_configs:
      - targets: ["alloy:12345"]
    metrics_path: "/metrics"
    scrape_interval: 5s  # Faster scraping
    relabel_configs:
      - target_label: service
        replacement: alloy

  - job_name: "otel-metrics"
    static_configs:
      - targets: ["alloy:9999"]
    metrics_path: "/metrics"
    scrape_interval: 5s  # Faster scraping
    relabel_configs:
      - target_label: service
        replacement: otel-collector

  # Keep other jobs as they were but with faster intervals
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 10s
    relabel_configs:
      - target_label: service
        replacement: prometheus

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    relabel_configs:
      - target_label: service
        replacement: tempo

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    relabel_configs:
      - target_label: service
        replacement: loki

  - job_name: "pyroscope"
    static_configs:
      - targets: ["pyroscope:4040"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    relabel_configs:
      - target_label: service
        replacement: pyroscope

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    relabel_configs:
      - target_label: service
        replacement: grafana