apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      timeInterval: "10s"  # Faster interval for better resolution
      scrapeInterval: "15s"
      queryTimeout: "60s"
      incrementalQueries: true
      minTimeInterval: "10s"  # Better for short intervals
      httpMethod: POST
      customQueryParameters: ""
      minStep: "1s"  # Fine granularity
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: Tempo
    secureJsonData: {}