{
 "title": "HRMS Backend New",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "name_space",
    "query": {
     "query": "label_values(service_namespace)"
    }
   },
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values({service_namespace=\"$name_space\"},service_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\", http_route!=\"/api/v2/ready\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\", http_route!=\"/api/v2/ready\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_request_duration_seconds_sum{service_name=\"$app_name\", http_route!=\"/api/v2/ready\"}) / sum by(uri) (http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/api/v2/ready\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=\"500\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"2.*\", uri!=\"/actuator/prometheus\", http_route!=\"/api/v2/ready\"}) / sum by(uri) (http_server_request_duration_seconds_count{service_name=\"$app_name\", uri!=\"/actuator/prometheus\", http_route!=\"/api/v2/ready\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{service_name=\"$app_name\", http_response_status_code=~\"5.*\", http_route!=\"\"}) / sum by(http_route) (http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\", http_route!=\"/api/v2/ready\"}[1m])) by(http_route, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$app_name\", http_route!=\"/actuator/prometheus\", http_route!=\"/api/v2/ready\"}[1m])) by(http_route, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{service_name=\"$app_name\", http_route!=\"/api/v2/ready\",http_route!=\"/*\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(severity) (rate({service_name=\"$name_space/$app_name\"} | json | severity != \"\" [1m]))"
    }
   ]
  },
  {
   "title": "Logs Apps",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$name_space/$app_name\"} | json | line_format \"{{.resources_service_name}}\\t{{.severity}}\\ttrace_id={{.traceid}}\\t{{.body}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}